<?xml version="1.0" encoding="UTF-8"?><testrun name="GreetingImplTest" project="Project_002_JUnit_Mockito" tests="3" started="3" failures="0" errors="2" ignored="0">
  <testsuite name="model.GreetingImplTest" time="11.662">
    <testcase name="greetShouldThrowException_For_NameIsNull" classname="model.GreetingImplTest" time="11.09">
      <error>java.lang.Exception: Unexpected exception, expected&lt;java.lang.IllegalArgumentException&gt; but was&lt;java.lang.Error&gt;&#13;
	at org.junit.internal.runners.MethodRoadie.runTestMethod(MethodRoadie.java:110)&#13;
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:79)&#13;
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:87)&#13;
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:77)&#13;
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:42)&#13;
	at org.junit.internal.runners.JUnit4ClassRunner.invokeTestMethod(JUnit4ClassRunner.java:88)&#13;
	at org.junit.internal.runners.JUnit4ClassRunner.runMethods(JUnit4ClassRunner.java:51)&#13;
	at org.junit.internal.runners.JUnit4ClassRunner$1.run(JUnit4ClassRunner.java:44)&#13;
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:27)&#13;
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:37)&#13;
	at org.junit.internal.runners.JUnit4ClassRunner.run(JUnit4ClassRunner.java:42)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
Caused by: java.lang.Error: Unresolved compilation problem: 
	The constructor GreetingImpl() is undefined
&#13;
	at model.GreetingImplTest.greetShouldThrowException_For_NameIsNull(GreetingImplTest.java:24)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:59)&#13;
	at org.junit.internal.runners.MethodRoadie.runTestMethod(MethodRoadie.java:98)&#13;
	... 16 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="greetShouldReturnValidOutput" classname="model.GreetingImplTest" time="0.571">
      <error>java.lang.Error: Unresolved compilation problem: 
	The constructor GreetingImpl() is undefined
&#13;
	at model.GreetingImplTest.greetShouldReturnValidOutput(GreetingImplTest.java:13)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:59)&#13;
	at org.junit.internal.runners.MethodRoadie.runTestMethod(MethodRoadie.java:98)&#13;
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:79)&#13;
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:87)&#13;
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:77)&#13;
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:42)&#13;
	at org.junit.internal.runners.JUnit4ClassRunner.invokeTestMethod(JUnit4ClassRunner.java:88)&#13;
	at org.junit.internal.runners.JUnit4ClassRunner.runMethods(JUnit4ClassRunner.java:51)&#13;
	at org.junit.internal.runners.JUnit4ClassRunner$1.run(JUnit4ClassRunner.java:44)&#13;
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:27)&#13;
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:37)&#13;
	at org.junit.internal.runners.JUnit4ClassRunner.run(JUnit4ClassRunner.java:42)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testExpected" classname="model.GreetingImplTest" time="0.0"/>
  </testsuite>
</testrun>
